#!/bin/sh
rm -rf output/acdc/*
rm -rf output/arc/*
rm ../../tmp/*
cd ../../
pwd
java -jar edu.usc.softarch.arcade.AcdcWithSmellDetection.jar subject_systems/httpd/src  subject_systems/httpd/output/acdc  ""  c
java -jar edu.usc.softarch.arcade.util.ldasupport.PipeExtractor.jar  subject_systems/httpd/src tmp
./ext-tools/mallet-2.0.7/bin/mallet import-dir --input subject_systems/httpd/src/ --remove-stopwords TRUE --keep-sequence TRUE --output tmp/topicmodel.data
./ext-tools/mallet-2.0.7/bin/mallet train-topics --input tmp/topicmodel.data --inferencer-filename tmp/infer.mallet --num-top-words 50 --num-topics 100 --num-threads 3 --num-iterations 100 --doc-topics-threshold 0.1
java -jar edu.usc.softarch.arcade.clustering.BatchClusteringEngine.jar  subject_systems/httpd/src   subject_systems/httpd/output/arc ""  c
mkdir subject_systems/httpd/output/arc/clusters
mkdir subject_systems/httpd/output/arc/deps
mkdir subject_systems/httpd/output/arc/smells
cd ../arcadepy
python src/arc/batchpackager.py --startdir ../../../arcade/subject_systems/httpd/output/arc/deps/ --pkgprefixes ""
